name: cli_repl
description: A simple library for CLI REPLs
version: 0.0.1
homepage: https://github.com/jathak/cli_repl
author: Jen Thakar <jen@jenthakar.com>

dependencies:
  async: ^1.13.3
  io: ^0.3.2

environment:
  sdk: '>=1.20.1 <2.0.0'
