name: cli_repl
description: A simple library for creating CLI REPLs
version: 0.1.3
homepage: https://github.com/jathak/cli_repl
author: Jen Thakar <jen@jenthakar.com>

dependencies:
  async: ">=1.13.3 <3.0.0"
  js: ^0.6.1
  io: ^0.3.2

dev_dependencies:
  grinder: ^0.8.1
  node_preamble: ^1.4.0
  test: ^0.12.34
  test_process: ^1.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'
